# Generated by Django 4.2.29 on 2026-04-06 18:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=200)),
                ('Type_of_complaint', models.CharField(choices=[('ClassRoom', 'Classroom'), ('Teacher', 'Teacher'), ('Management', 'Management'), ('College', 'College'), ('Other', 'Other')], max_length=50)),
                ('department', models.CharField(blank=True, choices=[('ComputerScience', 'Computer Science'), ('InformationScience', 'Information Science'), ('ElectronicsCommunication', 'Electronics & Communication'), ('Mechanical', 'Mechanical'), ('Administration', 'Administration'), ('General', 'General')], max_length=50, null=True)),
                ('Description', models.TextField(max_length=4000)),
                ('Time', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(1, 'Resolved'), (2, 'In Progress'), (3, 'Pending')], default=3)),
                ('remarks', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-Time'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('collegename', models.CharField(choices=[('College1', 'College 1'), ('College2', 'College 2')], max_length=50)),
                ('contactnumber', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')])),
                ('type_user', models.CharField(choices=[('student', 'Student'), ('teaching_staff', 'Teaching Staff'), ('non_teaching_staff', 'Non-Teaching Staff'), ('grievance', 'Grievance Cell Member')], default='student', max_length=25)),
                ('Branch', models.CharField(choices=[('ComputerScience', 'Computer Science'), ('InformationScience', 'Information Science'), ('ElectronicsCommunication', 'Electronics & Communication'), ('Mechanical', 'Mechanical')], default='ComputerScience', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.IntegerField(blank=True, choices=[(1, 'Resolved'), (2, 'In Progress'), (3, 'Pending')], null=True)),
                ('new_status', models.IntegerField(choices=[(1, 'Resolved'), (2, 'In Progress'), (3, 'Pending')])),
                ('remarks', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='GRsystem.complaint')),
            ],
            options={
                'verbose_name_plural': 'Complaint Histories',
                'ordering': ['-timestamp'],
            },
        ),
    ]
